spring:
  application:
    name: setTypeCode
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PWD}
    driverClassName: org.postgresql.Driver
  jpa:
    show-sql: false
logging:
  level:
    com.zaxxer.hikari: info
  file:
    name: /dev/work/logs/cpcsv.log
  appender.console.encoding: UTF-8
load:
  commitLimit: 10
  errorCsv: /dev/work/csv/errorData{0}.csv
  api:
    url: http://localhost:8080/address/formalize/
anorm:
  props.dir: /dev/work/anorm/props
  lic.path: /dev/work/anorm/license.key
  jmaster.dir: /dev/work/anorm/jmaster