spring:
  application:
    name: settypecode
  datasource:
    url: jdbc:postgresql://localhost:5432/kanjou_ph3
    username: postgres
    password: "x5WU7Xb3"
    driverClassName: org.postgresql.Driver
  jpa:
    show-sql: false
logging:
  level:
    com.zaxxer.hikari: warn
  file:
    name: C:\AIRead_ETL\logs\settypecode.log
    appender.console.encoding: UTF-8
csv:
  outPath: C:\AIRead_Report\CSV\
