spring.application.name=dateconverter

# メッセージソース設定
spring.messages.basename=messages
spring.messages.encoding=UTF-8
spring.messages.cache-duration=3600

# ログ設定
logging.file.path=logs
logging.file.name=${logging.file.path}/dateconverter.log
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n

# ログレベル
logging.level.root=INFO
logging.level.jp.co.ariseinnovation.dateconverter=DEBUG

# ログローテーション設定
logging.logback.rollingpolicy.file-name-pattern=${logging.file.path}/dateconverter-%d{yyyy-MM-dd}.log
logging.logback.rollingpolicy.max-history=30
# logging.logback.rollingpolicy.total-size-cap=1GB