spring:
  application:
    name: DataLink
  datasource:
    url: jdbc:postgresql://localhost:5432/kanjou_ph3
    username: postgres
    password: "x5WU7Xb3"
    driverClassName: org.postgresql.Driver
  jpa:
    show-sql: false
logging:
  level:
    com.zaxxer.hikari: warn
  file:
    name: C:/AIRead_ETL/logs/FixedAssetLink.log
    appender.console.encoding: UTF-8
