spring.application.name=loan_detail_merge_batch

# 入出力（既定値）
app.csv.input=sample.csv
app.csv.output=merged.csv
app.csv.debugZip=result.zip

# ログ最小化
logging.level.org.springframework.batch=INFO

# DataSourceの自動設定を無効化（DBなし）
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

# Spring Batchのジョブリポジトリをメモリに（DB不要）
spring.batch.job.repository.type=memory

spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.batch.job.enabled=false

server.port=0
